# Generated by Django 4.2.3 on 2023-07-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="آدرس ایمیل",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=60, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="شماره تلفن"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False, verbose_name="ادمین")),
            ],
            options={
                "verbose_name": "حساب کاربری",
                "verbose_name_plural": "حساب های کاربری",
            },
        ),
    ]
