# Generated by Django 4.2.3 on 2023-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_remove_order_addres_remove_order_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="012345", max_length=12),
        ),
    ]
