# Generated by Django 4.2.3 on 2023-08-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
