# Generated by Django 4.2.3 on 2023-08-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_order_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("discount", models.SmallIntegerField(default=0)),
                ("quantity", models.SmallIntegerField(default=1)),
            ],
        ),
    ]
